# Generated by Django 6.0.1 on 2026-01-29 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Carrera')),
                ('plan_key', models.CharField(max_length=20, unique=True, verbose_name='Clave del Plan')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Control')),
                ('current_semester', models.PositiveSmallIntegerField(verbose_name='Semestre Actual')),
                ('gender', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('student_type', models.CharField(choices=[('interno', 'Interno (Estudiante TEC)'), ('externo', 'Externo / Egresado')], default='interno', max_length=10, verbose_name='Tipo de Alumno')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.career', verbose_name='Carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_status', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Validado por Coordinación'), ('RECHAZADO', 'Rechazado / Corregir')], default='PENDIENTE', max_length=10, verbose_name='Estatus de Validación')),
                ('rejection_reason', models.TextField(blank=True, help_text='Explica al docente qué documento está mal o qué debe corregir.', null=True, verbose_name='Motivo de Rechazo')),
                ('category', models.CharField(choices=[('A', 'Categoría A'), ('B', 'Categoría B'), ('C', 'Categoría C')], max_length=1, verbose_name='Categoría Solicitada')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Banco')),
                ('clabe', models.CharField(max_length=18, verbose_name='CLABE Interbancaria')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('is_native', models.BooleanField(default=False, verbose_name='¿Es Nativo?')),
                ('language_level', models.CharField(blank=True, choices=[('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, null=True, verbose_name='Nivel MCER (Auto-declarado)')),
                ('academic_degree', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título/Grado')),
                ('ttc_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas TTC')),
                ('extra_certificate_name', models.CharField(blank=True, help_text='Ej: CELTA, DELTA, ICELT...', max_length=150, null=True, verbose_name='Nombre Certificación Extra (Cat B)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('INE', 'Identificación Oficial'), ('ACTA', 'Acta de Nacimiento'), ('CSF', 'Constancia Situación Fiscal'), ('TITULO', 'Título Profesional'), ('TTC', 'Constancia TTC'), ('TKT', 'Certificación TKT'), ('EXTRA', 'Certificación Especializada (Cat B)'), ('RES', 'Comprobante Residencia (Nativos)'), ('ACT', 'Evidencia de Actualización')], max_length=10)),
                ('file', models.FileField(upload_to='teacher_evidences/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('validation_status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10, verbose_name='Estatus')),
                ('rejection_reason', models.CharField(blank=True, help_text="Ej. 'Ilegible', 'Vencido', 'No corresponde'", max_length=255, null=True, verbose_name='Motivo de rechazo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='users.teacherprofile')),
            ],
        ),
    ]
